---
- hosts: openslides_pi_init_raspberry
  become: yes

  tasks:
  - name: Upgrade system (this can take some time)
    apt:
      update_cache: yes
      upgrade: dist

  - name: Create /root/.ssh
    file:
      path: /root/.ssh
      state: directory
      mode: 0700

  - name: Copy ssh key to root account
    copy:
      dest: /root/.ssh/authorized_keys
      mode: 0700
      src: ~/.ssh/id_rsa.pub

  - name: Disallow PasswordAuthentication for ssh
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: ^\#?PasswordAuthentication
      line: PasswordAuthentication no
    notify:
    - restart ssh

  handlers:
  - name: restart ssh
    service:
      name: ssh
      state: restarted
